#define USB_SUSPEND_WAKEUP_DELAY 500

#define DEBOUNCE 5
// #define USB_POLLING_INTERVAL_MS 3

// #define MASTER_LEFT
#define SPLIT_USB_DETECT

#define SERIAL_DEBUG

// oops, forgot to switch rx and tx pins in hardware >.>
#define SERIAL_USART_PIN_SWAP

// Start defining USART
#define SERIAL_USART_DRIVER SD1
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN B6
#define SERIAL_USART_RX_PIN B7
#define SERIAL_USART_TX_PAL_MODE 7
#define SELECT_SOFT_SERIAL_SPEED 2

#define SERIAL_USART_TIMEOUT 200

// Start defining RGB matrix stuff
// #define ENABLE_KEEB_RGB
#ifdef ENABLE_KEEB_RGB
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define RGB_MATRIX_SPLIT { 31, 25 }
#define SPLIT_LED_STATE_ENABLE
#define I2C_DRIVER I2CD2
#define I2C1_SCL_PIN B10
#define I2C1_SDA_PIN B11
#define RGB_MATRIX_LED_COUNT 31
#define IS31FL3729_I2C_ADDRESS_1 0x34
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define IS31FL3729_CONFIGURATION IS31FL3729_CONFIG_SWS_16_7
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#endif

