BOOTLOADER = stm32-dfu
CONSOLE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

CAPS_WORD_ENABLE = yes

BOOTMAGIC_ENABLE = yes
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = usart

# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_SPLIT = yes
# RGB_MATRIX_DRIVER = is31fl3729
